### ISSUE TITLE
Limit number of backups stored in backup directory

### ISSUE THREAD

**Issue by dano1066** [freekmurze/laravel-backup#14]
Is is possible to set how many backup files can be stored in the backup directory?

E.g. If i set the total to 5 and i ran a backup when there were already 5 backups in the directory it would automatically delete the oldest backup and create a new backup.

**Comment by freekmurze** [comment]
Currently the package does not clean the backup directory. You should schedule a job that cleans the directory yourself.

I can't give you a timeframe, but I'm planning to add this functionality in a future version.

**Comment by freekmurze** [comment]
Version 2.1.0 of the package introduces a command to clean up old backups
