### ISSUE TITLE
Database only backup

### ISSUE THREAD

**Issue by TheShiftExchange** [freekmurze/laravel-backup#15]
Is it possible to have an artisan command that is only for a DB Backup? Like in version 1?

I personally dont need my application backed up (I have it in Github) - I just want to dump my DB and save it locally + S3.

I can imagine other people would want to run the DB backup more frequently - and backup the app less often. So having the ability to run each command separately seems useful...?

**Comment by freekmurze** [comment]
For now set source.files.include to an empty in array in the config file and no files, except the dump of the db, will be backed up.

A separate command to backup the db makes sense. I'll add it in the near future.

**Comment by TheShiftExchange** [comment]
Cool - I'll do that - thanks.

p.s. I reckon have a command to backup only the app, a command to backup only the DB, and then a command which is for both to be run. That way it gives full flexibility for everyone...

**Comment by freekmurze** [comment]
Version 2.0.6 introduces this command:

`php artisan backup:run --only-db`

**Comment by TheShiftExchange** [comment]
@freekmurze - thanks - it works perfectly!

**Comment by achowdhury39** [comment]
D:\820\htdocs\payroll030323>php artisan backup:run --only-db
Starting backup...
Backup failed because: Path `D:\820\htdocs\payroll030323\storage\app/backup-temp\temp` already exists..

What should i do
please advice
