### ISSUE TITLE
Only able to backup one table in the database

### ISSUE THREAD

**Issue by olimorris** [freekmurze/laravel-backup#27]
Laravel-backup only seems to be able to make a mysql-dump of one of my nine database tables. I'm running Laravel 5 with MySQL (InnoDB) on Homestead. All other files appear to be backed up just fine

**Comment by MatthiasDeWinter** [comment]
This issue should be fixed in __version 2.2.1__.
Update your version and the problem should be resolved.

If this doesn't work let me know!

**Comment by olimorris** [comment]
Happy to confirm this is fixed. Thanks
