### ISSUE TITLE
Add filename prefix and suffix support

### ISSUE THREAD

**Issue by spaceemotion** [freekmurze/laravel-backup#29]
Hey, thanks for the package and the quick fix last time!

I've just added manual backup creation to my client's project, but would like to  distinguish between an automatically (using the scheduler) and a manually created one.
Instead of storing manually ones inside a database or a text file I would like to detect it through the filename.

Would it be possible to add prefix and suffix options to the `backup:run` command?
The resulting .zip would then look like this: `{prefix}20150421000009{suffix}.zip`. Adding prefixes would be as simple as running `php artisan backup:run --prefix "backup-" --suffix "-manual"`

Thanks in advance!

**Comment by freekmurze** [comment]
Great suggestion. These options have been added in version 2.3.0.

**Comment by spaceemotion** [comment]
Thank you very much!

**Comment by vesper8** [comment]
> Great suggestion. These options have been added in version 2.3.0.

@freekmurze were these options added and then removed? it seems like adding `--prefix` on the CLI doesn't work as of the latest version. It would be great if it did still work

**Comment by spaceemotion** [comment]
It seems like only `--filename` exists by now:

https://github.com/spatie/laravel-backup/blob/master/src/Commands/BackupCommand.php#L12
