### ISSUE TITLE
[Feature] mysqldump is not using extended inserts

### ISSUE THREAD

**Issue by spaceemotion** [freekmurze/laravel-backup#33]
Hello again!

System is working as smoothly as ever, but I noticed a very significant detail when importing a backed up database: All the insert queries generated by `mysqldump` are one-by-one. That makes importing even a small 15mb database one long "I'll-grab-a-coffee-then"-session.

Exporting the imported database using, for example, Sequel Pro (which generates one big insert query per table) takes 5 seconds, whereas the original database takes about 2-3 minutes!

This can be easily fixed by adding the `--extended-insert` parameter to the mysqldump command. However, I would make this optional using the configuration, as some servers might have trouble with such big queries.

More details can bee seen at the official documentation: https://dev.mysql.com/doc/refman/5.1/en/mysqldump.html#option_mysqldump_extended-insert

As always, thanks in advance!

**Comment by freekmurze** [comment]
I'll add this feature in the near future.

**Comment by freekmurze** [comment]
added in version 2.4.0
