### ISSUE TITLE
Backup to S3 using Laravel 5 system doesn't appear to work

### ISSUE THREAD

**Issue by olimorris** [freekmurze/laravel-backup#34]
Trying to backup my site to Amazon S3 doesn't appear to work and throws this error:
```
[Aws\S3\Exception\BucketAlreadyOwnedByYouException]                                 
  Your previous request to create the named bucket succeeded and you already own it.
```

Yet, when I run the following code in my application:
```
Route::any('/', function() {
    Storage::disk('website-backups')->put('help.txt', 'help.txt');

    if(Storage::disk('website-backups')->exists('help.txt'))
        return "Assert true";

    return "Assert this shizzle failed";
    
});
```
I assert true, that a file called 'help.txt' was created.

**Comment by freekmurze** [comment]
I can't reproduce this. Could you give me the entire debugtrace?

**Comment by olimorris** [comment]
How do I do that in the Terminal?

**Comment by freekmurze** [comment]
You could catch the exception in the code of your application
```php

Route::any('/', function() {
    try {
        Storage::disk('website-backups')->put('help.txt', 'help.txt');

        if(Storage::disk('website-backups')->exists('help.txt'))
            return "Assert true";

        return "Assert this shizzle failed";
    }
    catch(Exception $e)
    {
        echo $e->getMessage() . ' - ' . $e->getTraceAsString;
    }

});
```

**Comment by olimorris** [comment]
Sorry, yes when I run the code above in routes.php it works fine. The issue is when I run backup from the command line and I get the following error:
```
[Aws\S3\Exception\BucketAlreadyOwnedByYouException]                                 
  Your previous request to create the named bucket succeeded and you already own it.
```
Within filesystems.php, my disk is setup as below:
```
'website-backups' => [
            'driver' => 's3',
            'key'    => env('S3_ACCESS_KEY'),
            'secret' => env('S3_SECRET_KEY'),
            'region' => '',
            'bucket' => 'backup-of-website',
        ],
```

**Comment by freekmurze** [comment]
Maybe there's something wrong with your environment detection when using the CLI. Can you check on the command line (with ```php artisan tinker```) if ```Config::get('filesystems');``` and ```Config::get('laravel-backup');```return the right configuration values?

**Comment by olimorris** [comment]
It's most odd. Using tinker I can see the config's are being read correctly and my environment variables are being substituted in at the right places etc and my environment is set at local as per my ```.env```. 

I've tried changing my bucket permissions on AWS so that everyone can upload to it and still the same issue remains. Are your filesystem configs any different to mine?

**Comment by freekmurze** [comment]
I'm using the latest version of the package and backing up to s3 works fine

```bash
~ php artisan backup:run --only-db
Start backing up
Database dumped
Start zipping 1 files...
Zip created!
Start uploading backup to s3-filesystem...
Backup stored on s3-filesystem in file "backups/20150506233035.zip"
Backup successfully completed
```

In `config/filesystems.php` S3 is configured like this:

```php
's3' => [
    'driver' => 's3',
    'key'    => env('S3_KEY'),
    'secret' => env('S3_SECRET'),
    'region' => 'eu-west-1',
    'bucket' => env('S3_BUCKET')
],
```

I'm really puzzeled why it isn't working at your end. Are you sure you created the bucket on AWS in the region you specified in your config file?

**Comment by olimorris** [comment]
Finally...It seems that the region was correct but I changed my path config in ```laravel-backup.php``` to be ```'path' => '/backups'``` and that did the trick!

Really bizarre, seems like AWS didn't like putting files in the root of the bucket in this instance.

Cheers for your help Freekmurze! Oh and keep up the great posts on murze.be by the way!

**Comment by freekmurze** [comment]
No problem! I'm glad you could solve this issue.

**Comment by Premod1** [comment]
`      's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'throw' => false,
        ],`

this one my code. is not working

**Comment by Premod1** [comment]
's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'throw' => false,
        ],
        
        this one is why not working
