### ISSUE TITLE
local temporary files not cleaned?

### ISSUE THREAD

**Issue by geomagilles** [freekmurze/laravel-backup#35]
Hi, thanks for your package. I use it to store my backup files on S3. But unfortunately, temporary files are still created on /tmp and not deleted. This quickly saturate my filesystem :(

**Comment by freekmurze** [comment]
Normally the OS takes care of cleaning that directory. On Ubuntu it is cleared on every reboot by default. You can also [manually specify how frequently it should be cleared](http://askubuntu.com/questions/20783/how-is-the-tmp-directory-cleaned-up).

**Comment by groenewege** [comment]
Hi, I encountered the same issue.
Here is an example console task I added to my `app/Console/Kernel.php` file to clean up the temporary files.

    $schedule->exec("find /tmp -mtime +2 -name 'laravel-backup*' -and -exec rm {} ';'")->daily();

This wil remove temporary files from the `/tmp` directory that are older than 2 days and whose file name starts with "laravel-backup".
