### ISSUE TITLE
mysqldump alternative/additional option

### ISSUE THREAD

**Issue by barrymieny** [freekmurze/laravel-backup#5]
Could this package not support [github.com/ifsnop/mysqldump-php](https://github.com/ifsnop/mysqldump-php) in addition to the command-line mysqldump or is mysqldump-php not full-featured enough?

**Comment by freekmurze** [comment]
To be honest, I hadn't heard of that implementation. I'll take a look at it soon.

**Comment by freekmurze** [comment]
For the time being I'm gonna stick with the standard mysqldump binary. It is installed on most systems anyway.
