### ISSUE TITLE
use Storage

### ISSUE THREAD

**Issue by CawaKharkov** [freekmurze/laravel-backup#7]
I have a strange issue, when run **artisan backup:run**, I've have error, that class Storage not found. 
Works only if I change:
```use Storage;```
to
```use Illuminate\Support\Facades\Storage;```

**Comment by freekmurze** [comment]
Probably you'll have another class in your project that's named "Storage". I'll soon test the change to 
```use Illuminate\Support\Facades\Storage ``` and, if no problems arise, tag a version with this change.

**Comment by freekmurze** [comment]
Fixed in version 2.0.5
