### ISSUE TITLE
Laravel 4?

### ISSUE THREAD

**Issue by KuenzelIT** [freekmurze/laravel-backup#8]
Hi,

is this package limited to Laravel 5 or may there be a way to use it with Laravel 4 too?

Thanks!

**Comment by freekmurze** [comment]
Hi,

because the package uses some Laravel 5 specific features (the built-in integration with flysystem) there's no support for Laravel 4.

If you want to backup your db using L4 I can recommend [this package](https://github.com/schickling/laravel-backup)
