### ISSUE TITLE
Composer requirements

### ISSUE THREAD

**Issue by alxy** [freekmurze/laravel-backup#9]
Hi,
is there any reason you require orchestra/testbench in you composer.json: https://github.com/freekmurze/laravel-backup/blob/master/composer.json#L26
This leads to the download of the entire laravel/framework (and dependencies) if I use this app for example in an OctoberCMS plugin: https://github.com/alxy/oc-backup-plugin

Couldn't you at least put this in require-dev?

**Comment by freekmurze** [comment]
Hi, 

this is corrected in version 2.0.3. 

Keep in mind though that this package is intended to be used in Laravel 5. Some [L5 specific functionality](http://laravel.com/docs/5.0/filesystem) is used. I haven't tested it in OctoberCMS.

**Comment by alxy** [comment]
Thanks!
